apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-workflow-role
rules:
  - verbs:
      - '*'
    apiGroups:
      - argoproj.io
    resources:
      - eventsources
      - sensors
      - workflows
      - workfloweventbindings
      - workflowtemplates
      - workflowtaskresults
      - cronworkflows
      - clusterworkflowtemplates
      - pods
      - pods/exec
      - pods/log
      - persistentvolumes
      - persistentvolumes
      - persistentvolumeclaims
      - persistentvolumeclaims/status
  - verbs:
      - '*'
    apiGroups:
      - ""
      - core
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - pods
      - pods/exec
      - pods/log
      - namespaces
      - nodes
      - storageclasses
      - persistentvolumes
      - persistentvolumes
      - persistentvolumeclaims
      - persistentvolumeclaims/status

---

#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#  name: argo-cluster-role-test
#  namespace: argo-events
#rules:
#  - apiGroups: ["argoproj.io"] # 必須明確指定 API Group
#    resources: ["workflows"]
#    verbs: ["get", "list", "create", "delete", "patch"] # 視需求添加動作
#  - apiGroups: [""] # 示例：基礎 Kubernetes 資源
#    resources: ["pods", "pods/log", "secrets", "configmaps"]
#    verbs: ["get", "watch", "list", "create", "delete", "patch"]