apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-workflow-role-binding
subjects:
  - kind: ServiceAccount
    name: test-work
    namespace: test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-workflow-role

#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRoleBinding
#metadata:
#  name: argo-cluster-role-binding-test
#roleRef:
#  apiGroup: rbac.authorization.k8s.io
#  kind: ClusterRole
#  name: argo-cluster-role-test
#subjects:
#  - kind: ServiceAccount
#    name: default
#    namespace: {{ .Values.namespace | quote }}
