apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: test-workflow
#  namespace: argo-events
spec:
  entrypoint: main
arguments:
  parameters:
    - name: input
      value: ""  # 默認值，會被觸發器的數據覆蓋
  templates:
    - name: main
      steps:
        - - name: step1
            template: whalesay
        - - name: step2
            template: echo

    - name: whalesay
      container:
        image: {{ .Values.images.test1 }}
        command: ["/bin/sh", "-c"]
        args: ["echo Hello from Workflow!",'{{"{{"}}workflow.parameters.input{{"}}"}}']

    - name: echo
      container:
        image: {{ .Values.images.test2 }}
        command: ["/bin/sh", "-c"]
        args: ["echo This is step 2."]