apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: test-workflow
#  namespace: argo-events
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: input
        value: ""  # 默認值，會被觸發器的數據覆蓋
  templates:
  - name: main
    inputs:
      parameters:
        - name: message
          value: hello world
    steps:
      - - name: step1
          template: test1
      - - name: step2
          template: test2
  - name: test1
    container:
      image: busybox
      command: [echo]
      args: ['{{"{{"}}workflow.parameters.input{{"}}"}}']

  - name: test2
    container:
      image: {{ .Values.images.test2 }}
      command: ["/bin/sh", "-c"]
      args: ["echo This is step 2."]